# Generated by Django 5.1.3 on 2025-01-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=100)),
                ('cardBalance', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
